<?php
use fhnw\gii\generators\game\ModuleGenerator;

/** @var $generator ModuleGenerator */
echo "<?php\n"
?>
/**
 * Configuration file for `yii message/extract` command.
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 * You can use 'yii message/config-template' command to create template configuration file with detailed description for each parameter.
 * ```sh
 * yii message/extract translate.php
 * ```
 *
 * @author {{USER_NAME}} <{{USER_MAIL}}>
 */
return [
  'color'            => true,
  'languages'        => ['de', 'en-UK',],
  'messagePath'      => '<?= $generator->moduleClass->getAlias('messages') ?>',
  'sourceLanguage'   => 'en-UK',
  'sourcePath'       => '<?= $generator->moduleClass->getAlias() ?>',
  'translator'       => ['<?= $generator->moduleClass->getModuleName() ?>::t'],
  'overwrite'        => true,
  'removeUnused'     => false,
  'markUnused'       => true,
  'format'           => 'php',
  'catalog'          => 'messages',
  'ignoreCategories' => [],
  'fileMap'          => []
];
