name: Create a new Game Module

on:
  issues:
    types:
      - opened

concurrency: 'main'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/create-game-module.yml

      - name: save results
        run: echo '${{ steps.issue-parser.outputs.jsonString }}' > data.json

      - run: node make.js

      - name: Install dependencies
        uses: php-actions/composer@v6

      - run: |
          chmod +x ./generate.sh && \
          ./generate.sh

          # - run: node ./place-order.js

          # - name: Commit changes
        #   shell: bash
        #   run: |
        #     git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
        #     git config --global user.name "github-actions[bot]" && \
        # git add README.md && \
        # git commit -m 'Place order' && \
        # git push


        # - uses: peter-evans/close-issue@v3
        # with:
        # comment: Pizza time! Check out the <a href="../">README</a>.
